version: "3.8"

services:
  discovery:
    container_name: service-discovery
    build:
      context: ./lca-registry
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  gateway:
    container_name: service-gateway
    build:
      context: ./lca-gateway
      dockerfile: Dockerfile
    ports:
      - "8762:8762"
    depends_on:
      - discovery
    links:
      - discovery:discovery

  customers:
    container_name: service-customers-api
    build:
      context: ./lca-customer
      dockerfile: Dockerfile
    environment: 
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_DATASOURCE_INITIALIZATION-MODE: ${SPRING_DATASOURCE_INITIALIZATION}
      SPRING_JPA_HIBERNATE_DDL-AUTO: ${SPRING_JPA_HIBERNATE_DLL}
    ports:
      - "8200:8200"
    depends_on:
      - discovery
      - gateway
      - customers-db
    links:
      - discovery:discovery
      - customers-db

  customers-db:
    container_name: service-customers-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql

  frontend:
    container_name: service-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - discovery
      - gateway
      - customers-db
    links:
      - gateway
