version: "3.8"

services:
  discovery:
    container_name: service-discovery
    build:
      context: ./lca-registry
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  gateway:
    container_name: service-gateway
    build:
      context: ./lca-gateway
      dockerfile: Dockerfile
    ports:
      - "8762:8762"
    depends_on:
      - discovery
    links:
      - discovery:discovery

  customers:
    container_name: service-customers-api
    build:
      context: ./lca-customer
      dockerfile: Dockerfile
    ports:
      - "8200:8200"
    depends_on:
      - discovery
      - gateway
      - customers-db
    links:
      - discovery:discovery
      - customers-db

  customers-db:
    container_name: service-customers-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      - '3306'

  frontend:
    container_name: service-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - discovery
      - gateway
      - customers-db
    links:
      - gateway
