version: "3.8"
services:
  lca-gateway:
    container_name: lca-gateway
    build: .
    ports:
      - '8762:8762'
    expose:
      - 8762
    links:
      - lca-registry
    depends_on:
      - lca-registry
