name: IT Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Run tests
        run: |
          cd ${{ env.GITHUB_WORKSPACE }}
          git clone https://ansotolab:${{ secrets.PAT }}@github.com/ansotolab/lca-gateway.git
          ls
          cd ${{ env.GITHUB_WORKSPACE }}/lca-gateway
          mvn spring-boot:run
          cd ${{ env.GITHUB_WORKSPACE }}
          git clone https://ansotolab:${{ secrets.PAT }}@github.com/ansotolab/lca-registry.git
          ls
          cd ${{ env.GITHUB_WORKSPACE }}/lca-registry
          mvn spring-boot:run
          cd ${{ env.GITHUB_WORKSPACE }}
          npm install -g newman
          newman run postman-customer.json