name: IT Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 'Downloading Gateway'
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ansotolab/lca-gateway
          path: ../lca-gateway
      - name: 'Run Gateway'
        run: cd ../lca-gateway && mvn spring-boot:run
      - name: 'Downloading Registry'
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ansotolab/lca-registry
          path: ../lca-registry
          - name: 'Run Registry'
            run: cd ../lca-registry && mvn spring-boot:run
      - name: 'Change to lca-folder folder'
          run: cd ../lca-customer
      - name: 'IT Postman Tests'
        uses: matt-ball/newman-action@master
        with:
          collection: postman-customer.json