name: IT Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Download Gateway'
        run: |
          cd ${{ env.HOME }}
          git clone https://ansotolab:${{ secrets.PAT }}@github.com/ansotolab/lca-gateway.git
          pwd
          ls
      - name: 'Run Gateway'
        run: cd ${{ env.HOME }}/lca-gateway && mvn spring-boot:run
      - name: 'Download Registry'
        run: cd ${{ env.HOME }} && git clone https://ansotolab:${{ secrets.PAT }}@github.com/ansotolab/lca-registry.git
      - name: 'Run Registry'
        run: cd ${{ env.HOME }}/lca-registry && mvn spring-boot:run
      - name: 'Change to lca-customer folder'
        run: cd ${{ env.GITHUB_WORKSPACE }}
      - name: 'IT Postman Tests'
        uses: matt-ball/newman-action@master
        with:
          collection: postman-customer.json