name: IT Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Downloading Gateway'
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ansotolab/lca-gateway
          path: ${{ env.HOME }}
      - name: 'Run Gateway'
        run: cd ${{ env.HOME }}/lca-gateway && mvn spring-boot:run
      - name: 'Downloading Registry'
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ansotolab/lca-registry
          path: ${{ env.HOME }}
      - name: 'Run Registry'
        run: cd ${{ env.HOME }}/lca-registry && mvn spring-boot:run
      - name: 'Change to lca-folder folder'
        run: cd ${{ env.GITHUB_WORKSPACE }}
      - name: 'IT Postman Tests'
        uses: matt-ball/newman-action@master
        with:
          collection: postman-customer.json