name: IT Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Run tests
        run: |
          docker-compose up -d
          echo "Esperando 90 segundos."
          sleep 90
          docker ps -a
          npm install -g newman
          newman run it-postman/postman-customer.json
